### ISSUE TITLE
Login not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by yichenzhu1337** [20lives/FrontendMastersDownloader#35]
It seems to work on Mac, but does not seem to work on Linux. Any idea why?

**Comment by coolsaint** [comment]
It is not working anywhere for me. It worked in windows at first. looks like frontendmasters.com has changed their api endpoint. 
I still don't understand how the author of the repository got the api endpoint in the first place! 

`const baseUrl = 'https://api.frontendmasters.com/v2.2/m/';`

I am getting parse error for the json response in login.

`UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input`

**Comment by markadrake** [comment]
Here to confirm that login doesn't work on multiple systems - including Windows and macOS. This is not specific to Ubuntu, and as @coolsaint pointed out is an issue with the endpoint.

**Comment by yichenzhu1337** [comment]
@20lives I noticed that the frontendmasters base endpoint url is:

`const baseUrl = 'https://api.frontendmasters.com/v2.2/m/';`

from your `constants.js` file

https://github.com/20lives/FrontendMastersDownloader/blob/master/src/constants.js#L1

I tried doing a quick google search for any online documentation regarding this URL, but couldn't find any.

Any chance you can redirect me to those docs? I want to see if I can debug/fix this issue.

@markadrake @coolsaint @Ali-Shaikh maybe one of you guys know and can direct me to a known online documentation somewhere online?

**Comment by markadrake** [comment]
Most likely this API endpoint was sniffed out via the Android app. No public documentation exists from what I can tell. It's out of my realm of expertise but using something like an Android Simulator and wireshark may net us some more details?

**Comment by 20lives** [comment]
Hi all, @markadrake is the closest.
This project is a result of reverse engineering of the android app.
Sniffling the network won't do much good since the data is encrypted (and there are additional protection methods)

The reason this isn't working is that frontendmasters blocked it. Using this tools is against their term of services since users can abuse their content.

This is probably fixable but takes some time which I can't spare at the moment.

**Comment by 20lives** [comment]
We have a fix
The login is probably broken because frontendmasters updated their API version.
just remove `~/.frontendmasters-downloader` file and try again.

**Comment by coolsaint** [comment]
yes removing` .frontendmaster-downloader`  file got me the script working again. But unfortunately within 5 minutes I got my account suspended. They sent me an email which clearly states their point : ( They found the loophole! )

> Your account has been suspended for scripting or otherwise initiating downloads against our web player APIs. We'd appreciate it if you would halt your script or disable any browser plugin responsible for the activity. Offline viewing is available through our iOS and Android apps. If you have any questions, please review our Terms of Service.
> 
> You'll need to respond in the affirmative before your account will be restored.

**Comment by markadrake** [comment]
Highly suggest not interacting with this repo using the same email account as your frontend masters login. 

They sent me a suspension as well. I did nothing but test this script to see why login access stopped working. They could not provide any detailed records of me downloading videos. I couldn't log in, so it's not even debatable whether or not I downloaded their training videos. 

**If you use this script in any way, even for testing purposes your account will be flagged now.**

Best of luck.

**Comment by damdiaz** [comment]
@20lives see this mail:

Your account has been suspended for scripting or otherwise initiating downloads against our web player APIs. We'd appreciate it if you would halt your script or disable any browser plugin responsible for the activity. Offline viewing is available through our iOS and Android apps. If you have any questions, please review our Terms of Service. 
You'll need to respond in the affirmative before your account will be restored.

Any Solution please
